{ "update_id" => 11,
  "message" => { "message_id" => 99,
                 "from" => { "id" => 77,
                             "is_bot" => false,
                             "first_name" => "a",
                             "username" => "aa",
                             "language_code" => "zh-hans" },
                 "chat" => { "id" => 77,
                             "first_name" => "a",
                             "username" => "aa",
                             "type" => "private" },
                 "date" => 101,
                 "text" => "https://twitter.com/xxxxxxxx",
                 "entities" => [{ "offset" => 0, "length" => 67, "type" => "url" }] } }
